FROM ubuntu:latest

RUN apt-get update

RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y ruby
RUN apt-get install -y python
RUN apt-get install -y npm
RUN apt-get install -y golang-go
RUN apt-get install -y nodejs
